config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: {minimum: 3}
    validates :body, presence: true
    validates :writer_name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
#require '../models/article'

class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def index
       #CRUD Operations of Active Record 
       @articles = Article.all.order :id
    end

    def show
    end

    def new
       @article = Article.new
    end

    def create
       #binding.break

       if @article.save 
        redirect_to articles_path
       else
        render :new
       end
    end

    def edit
    end

    def update

        if @article.update(article_params) 
            redirect_to article_path(@article), notice: "Note is successfully updated"
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        @article.destroy!
        redirect_to articles_url, notice: "Article #{@article.id} was successfully destroyed", status: :see_other
      end      

    private

    def article_params
        params.require(:article).permit(:title, :body, :writer_name)
    end

    def set_article
        @article = Article.find(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end
  
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
    end

    private
      def comment_params
        params.require(:comment).permit(:body, )
      end
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!
    redirect_to posts_url, notice: "Post was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
  <% if @article.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %> <br/>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :writer_name %> <br/>
    <%= form.text_field :writer_name %>
  </p>
  <p>
    <%= form.label :body %> <br/>
    <%= form.text_field :body %>
  </p>

  <p>
    <%= form.submit "Submit" %>
  </p>
<% end %>

<div>
  <%= link_to 'Back to article', articles_path %>
</div>

app/views/articles/edit.html.erb
<h1>Edit</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to 'Show this article', @article %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>


<h2>Articles</h2>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Author</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td><%= article.id%></td>
            <td><%= link_to article.title, article %></td>
            <td><%= article.writer_name%></td>
            <td><%= article.body%></td>
        </tr>
        <% end %>
    </tbody>
</table>

<div>
    <%= link_to 'New Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<h2>New Article</h2>

<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<h2><%= @article.title %></h2>
<h3>by: <%= @article.writer_name %></h3>
<p><%= @article.body %></p>

<div>
    <%= link_to 'Edit', edit_article_path(@article) %> | 
    <%= link_to 'Back', articles_path %> |
    <%= button_to 'Destroy', @article, method: :delete, data: {turbo_confirm: "Are you sure?"}%>
</div>


<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment</h2>
<%= render 'comments/form', article: @article %>

app/views/comments/_comment.html.erb
    <p>
        <strong>Anonymous:</strong>
        <%= comment.body %>
    </p>

<%= button_to "Destroy Comment", [comment.article, comment], method: :delete, data: {
                  turbo_confirm: "Are you sure?"
                } %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/special_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- <h1>e2 ako si natoy</h1> -->
    <%= yield %> <!-- ur action template gets rendered here -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Name:</strong>
    <%= post.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>